export interface HttpHeaders {
  [header: string]: string | string[] | undefined;
}

export interface RequestHttpHeaders extends HttpHeaders {
  "a-im"?: string;
  accept?: string;
  "accept-charset"?: string;
  "accept-datetime"?: string;
  "accept-encoding"?: string;
  "accept-language"?: string;
  "access-control-request-method"?: string;
  "access-control-request-headers"?: string;
  authorization?: string;
  "cache-control"?: string;
  connection?: string;
  permanent?: string;
  "content-length"?: string;
  "content-md5"?: string;
  "content-type"?: string;
  cookie?: string;
  date?: string;
  expect?: string;
  forwarded?: string;
  from?: string;
  host?: string;
  "http2-settings"?: string;
  "if-match"?: string;
  "if-modified-since"?: string;
  "if-none-match"?: string;
  "if-range"?: string;
  "if-unmodified-since"?: string;
  "max-forwards"?: string;
  origin?: string;
  pragma?: string;
  "proxy-authorization"?: string;
  range?: string;
  referer?: string;
  te?: string;
  trailer?: string;
  "transfer-encoding"?: string;
  "user-agent"?: string;
  upgrade?: string;
  via?: string;
  warning?: string;
}

export interface ResponseHttpHeaders extends HttpHeaders {
  accept?: string;
  "accept-language"?: string;
  "accept-patch"?: string;
  "accept-ranges"?: string;
  "access-control-allow-credentials"?: string;
  "access-control-allow-headers"?: string;
  "access-control-allow-methods"?: string;
  "access-control-allow-origin"?: string;
  "access-control-expose-headers"?: string;
  "access-control-max-age"?: string;
  age?: string;
  allow?: string;
  "alt-svc"?: string;
  authorization?: string;
  "cache-control"?: string;
  connection?: string;
  "content-disposition"?: string;
  "content-encoding"?: string;
  "content-language"?: string;
  "content-length"?: string;
  "content-location"?: string;
  "content-range"?: string;
  "content-type"?: string;
  cookie?: string;
  date?: string;
  expect?: string;
  expires?: string;
  forwarded?: string;
  from?: string;
  host?: string;
  "if-match"?: string;
  "if-modified-since"?: string;
  "if-none-match"?: string;
  "if-unmodified-since"?: string;
  "last-modified"?: string;
  location?: string;
  pragma?: string;
  "proxy-authenticate"?: string;
  "proxy-authorization"?: string;
  "public-key-pins"?: string;
  range?: string;
  referer?: string;
  "retry-after"?: string;
  "set-cookie"?: string[];
  "strict-transport-security"?: string;
  tk?: string;
  trailer?: string;
  "transfer-encoding"?: string;
  upgrade?: string;
  "user-agent"?: string;
  vary?: string;
  via?: string;
  warning?: string;
  "www-authenticate"?: string;
  [header: string]: string | string[] | undefined;
}
