/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  someSidebar: {
    Welcome: [
      "welcome/getting-started",
      "welcome/philosophy",
      "welcome/core-concepts",
      "welcome/testability",
      "welcome/runtime-independence",
      "welcome/symmetry"
    ],
    Guides: [
      "guides/your-first-handler",
      "guides/binding-to-node-js-server",
      "guides/request-and-response",
      "guides/filters",
      "guides/routing",
      "guides/async-iterators-instead-of-streams",
      "guides/unit-tests"
    ],
    "API Reference": [
      "reference/http",
      "reference/body",
      "reference/router",
      "reference/node-js"
    ],
    Contributing: [
      "contributing/we-need-help",
      "contributing/project-structure"
    ]
  }

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
